use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentInfo {
    pub id: String,
    pub name: String,
    pub role: String,
    pub color: String,
    pub is_starter: bool,
}

pub fn get_all_agents() -> Vec<AgentInfo> {
    vec![
        AgentInfo {
            id: "41fb69c1-4189-7b37-f117-bcaf1e96f1bf".to_string(),
            name: "Astra".to_string(),
            role: "Controller".to_string(),
            color: "#9B59B6".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "5f8d3a7f-467b-97f3-062c-13acf203c006".to_string(),
            name: "Breach".to_string(),
            role: "Initiator".to_string(),
            color: "#EB3B5A".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "9f0d8ba9-4140-b941-57d3-a7ad57c6b417".to_string(),
            name: "Brimstone".to_string(),
            role: "Controller".to_string(),
            color: "#DE6433".to_string(),
            is_starter: true,
        },
        AgentInfo {
            id: "22697a3d-45bf-8dd7-4fec-84a9e28c69d7".to_string(),
            name: "Chamber".to_string(),
            role: "Sentinel".to_string(),
            color: "#F7B731".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "1dbf2edd-4729-0984-3115-daa5eed44993".to_string(),
            name: "Clove".to_string(),
            role: "Controller".to_string(),
            color: "#FF9EBB".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "117ed9e3-49f3-6512-3ccf-0cada7e3823b".to_string(),
            name: "Cypher".to_string(),
            role: "Sentinel".to_string(),
            color: "#D1D8E0".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "cc8b64c8-4b25-4ff9-6e7f-37b4da43d235".to_string(),
            name: "Deadlock".to_string(),
            role: "Sentinel".to_string(),
            color: "#8854D0".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "dade69b4-4f5a-8528-247b-219e5a1facd6".to_string(),
            name: "Fade".to_string(),
            role: "Initiator".to_string(),
            color: "#778CA3".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "e370fa57-4757-3604-3648-499e1f642d3f".to_string(),
            name: "Gekko".to_string(),
            role: "Initiator".to_string(),
            color: "#A3CB38".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "95b78ed7-4637-86d9-7e41-71ba8c293152".to_string(),
            name: "Harbor".to_string(),
            role: "Controller".to_string(),
            color: "#0FB9B1".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "0e38b510-41a8-5780-5e8f-568b2a4f2d6c".to_string(),
            name: "Iso".to_string(),
            role: "Duelist".to_string(),
            color: "#5758BB".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "add6443a-41bd-e414-f6ad-e58d267f4e95".to_string(),
            name: "Jett".to_string(),
            role: "Duelist".to_string(),
            color: "#FFFFFF".to_string(),
            is_starter: true,
        },
        AgentInfo {
            id: "601dbbe7-43ce-be57-2a40-4abd24953621".to_string(),
            name: "KAY/O".to_string(),
            role: "Initiator".to_string(),
            color: "#45AAF2".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "1e58de9c-4950-5125-93e9-a0aee9f98746".to_string(),
            name: "Killjoy".to_string(),
            role: "Sentinel".to_string(),
            color: "#FED330".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "7c8a4701-4de6-9355-b254-e09bc2a34b72".to_string(),
            name: "Miks".to_string(),
            role: "Controller".to_string(),
            color: "#3498DB".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "bb2a4828-46eb-8cd1-e765-15848195d751".to_string(),
            name: "Neon".to_string(),
            role: "Duelist".to_string(),
            color: "#2BCBBA".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "8e253930-4c05-31dd-1b6c-968525494517".to_string(),
            name: "Omen".to_string(),
            role: "Controller".to_string(),
            color: "#4B6584".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "eb93336a-449b-9c1b-0a54-a891f7921d69".to_string(),
            name: "Phoenix".to_string(),
            role: "Duelist".to_string(),
            color: "#F67243".to_string(),
            is_starter: true,
        },
        AgentInfo {
            id: "f94c3b30-42be-e959-889c-5aa313dba261".to_string(),
            name: "Raze".to_string(),
            role: "Duelist".to_string(),
            color: "#FA8231".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "a3bfb853-43b2-7238-a4f1-ad90e9e46bcc".to_string(),
            name: "Reyna".to_string(),
            role: "Duelist".to_string(),
            color: "#A55EEA".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "569fdd95-4d10-43ab-ca70-79becc718b46".to_string(),
            name: "Sage".to_string(),
            role: "Sentinel".to_string(),
            color: "#56E0D2".to_string(),
            is_starter: true,
        },
        AgentInfo {
            id: "6f2a04ca-43e0-be17-7f36-b3908627744d".to_string(),
            name: "Skye".to_string(),
            role: "Initiator".to_string(),
            color: "#26DE81".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "320b2a48-4d9b-a075-30f1-1f93a9b638fa".to_string(),
            name: "Sova".to_string(),
            role: "Initiator".to_string(),
            color: "#2C6DE8".to_string(),
            is_starter: true,
        },
        AgentInfo {
            id: "b444168c-4e35-8076-db47-ef9bf368f384".to_string(),
            name: "Tejo".to_string(),
            role: "Initiator".to_string(),
            color: "#E58E26".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "92eeef5d-43b5-1d4a-8d03-b3927a09034b".to_string(),
            name: "Veto".to_string(),
            role: "Sentinel".to_string(),
            color: "#6C5CE7".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "707eab51-4836-f488-046a-cda6bf494859".to_string(),
            name: "Viper".to_string(),
            role: "Controller".to_string(),
            color: "#20BF6B".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "efba5359-4016-a1e5-7626-b1ae76895940".to_string(),
            name: "Vyse".to_string(),
            role: "Sentinel".to_string(),
            color: "#9980FA".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "df1cb487-4902-002e-5c17-d28e83e78588".to_string(),
            name: "Waylay".to_string(),
            role: "Duelist".to_string(),
            color: "#E74C3C".to_string(),
            is_starter: false,
        },
        AgentInfo {
            id: "7f94d92c-4234-0a36-9646-3a87eb8b5c89".to_string(),
            name: "Yoru".to_string(),
            role: "Duelist".to_string(),
            color: "#3867D6".to_string(),
            is_starter: false,
        },
    ]
}
